<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Core.MSSQL.SqlHelper" Version="1.0.3" />
    <PackageReference Include="EPPlus" Version="7.5.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="172.52.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SQLHelper.DB" Version="5.0.14" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
  </ItemGroup>

</Project>
